name: demo_blutooth_print
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bluetooth_print: ^4.3.0
  intl: ^0.18.0
  screenshot: ^1.3.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0
  device_info_plus: ^8.1.0
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/qr.png
    - assets/images/guide3.png
    - assets/images/bluetooth_print.png
